set nocompatible
set rtp+=$HOME/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'The-NERD-tree'
map <F2> :NERDTreeToggle<CR>
let NERDTreeWinSize=25 
call vundle#end()
 
"新建.c,.h,.sh,.java文件，自动插入文件头 
autocmd BufNewFile *.cpp,*.[ch],*.sh,*.java exec ":call SetTitle()" 
""定义函数SetTitle，自动插入文件头 
func SetTitle() 
	"如果文件类型为.sh文件 
	if &filetype == 'sh' 
		call setline(1, "##########################################################################") 
		call append(line("."), "# File Name: ".expand("%")) 
		call append(line(".")+1, "# Author: jianjie") 
		call append(line(".")+2, "# mail: 1051532926@qq.com") 
		call append(line(".")+3, "# Created Time: ".strftime("%c")) 
		call append(line(".")+4, "#########################################################################") 
		call append(line(".")+5, "#!/bin/zsh")
		call append(line(".")+6, "PATH=/home/edison/bin:/home/edison/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/work/tools/gcc-3.4.5-glibc-2.3.6/bin")
		call append(line(".")+7, "export PATH")
		call append(line(".")+8, "")
	else 
		call setline(1, "/*************************************************************************") 
		call append(line("."), "	> File Name: ".expand("%")) 
		call append(line(".")+1, "	> Author: jianjie") 
		call append(line(".")+2, "	> Mail: 1051532926@qq.com ") 
		call append(line(".")+3, "	> Created Time: ".strftime("%c")) 
		call append(line(".")+4, " ************************************************************************/") 
		call append(line(".")+5, "")
	endif
	if &filetype == 'cpp'
		call append(line(".")+6, "#include<iostream>")
    	call append(line(".")+7, "using namespace std;")
		call append(line(".")+8, "")
	endif
	if &filetype == 'c'
		call append(line(".")+6, "#include<stdio.h>")
		call append(line(".")+7, "int main(int argc,char *argv[])")
		call append(line(".")+8,"{")
		call append(line(".")+9,"    ")
		call append(line(".")+10,"    return 0;")
		call append(line(".")+11,"}")
	endif
	"	if &filetype == 'java'
	"		call append(line(".")+6,"public class ".expand("%"))
	"		call append(line(".")+7,"")
	"	endif
	"新建文件后，自动定位到文件末尾
	autocmd BufNewFile * normal G
endfunc 

autocmd BufReadPost *.c nmap <F5> :call Gcc()
fu Gcc()
exec "silent !gcc -o " . expand("%:t:r") . " %"
exec "!./" . expand("%:t:r")
endf
nmap <leader>w :w!<cr>
nmap <leader>q :qa!<cr>
nmap <leader>f :find<cr>
map <C-A> ggVGY
map! <C-A> <Esc>ggVGY
map <F12> gg=G
vmap <C-c> "+y
 
set autoread
autocmd FileType c,cpp map <buffer> <leader><space> :w<cr>:make<cr>
filetype plugin on
set nobackup
set autowrite
set autoindent
set tabstop=4
set number
set noswapfile
set enc=utf-8
set langmenu=zh_CN.UTF-8
set helplang=cn
filetype on
filetype plugin on
filetype indent on
set backspace=2
set mouse=a
set selectmode=mouse,key
set completeopt=longest,menu,preview